[package]
name = "zscan-core"
description = "Find, extract and reinject compressed streams inside binary files"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
crc32fast.workspace = true
libz-sys.workspace = true
memmap2.workspace = true
miniz_oxide.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
zscan-fixtures.workspace = true
